#!/bin/bash
# =============================================================================
# modernized tree (<product>-modernized) setup script
# =============================================================================
#
# Run during Phase 3 Step 1 (when acquiring source).
# Prepares a working tree from the source tree and initializes it as an
# independent git repository.
#
#   - If the source tree is git-managed: clone to carry over history,
#     cut a work branch modernize/<target>, and tag the starting point modernize-base.
#   - If the source tree is not git-managed: copy, git init, initial commit + modernize-base.
#
# Placement: the created <product>-modernized is placed in the same parent directory
# as the source tree (i.e. alongside the migration project).
#
# Usage:
#   ./setup-modernized.sh <source-path> <target> [base-ref]
#     <source-path> : Path to the source tree (git working tree or ordinary directory)
#     <target>      : Branch name suffix. Convention <target-os>-<arch>
#                     e.g. amzn2023-x86_64-lp64  -> branch modernize/amzn2023-x86_64-lp64
#     [base-ref]    : Tag/commit to use as the starting point (default: current HEAD of the source tree)
#
# Example:
#   ./setup-modernized.sh /path/to/workspace/myapp-1.0 amzn2023-x86_64-lp64 myapp-1.0
# =============================================================================
set -euo pipefail

SRC="${1:-}"
TARGET="${2:-}"
BASE_REF="${3:-}"

if [ -z "$SRC" ] || [ -z "$TARGET" ]; then
  echo "Usage: $0 <source-path> <target> [base-ref]"
  echo "  Example: $0 /path/to/workspace/myapp-1.0 amzn2023-x86_64-lp64 myapp-1.0"
  exit 1
fi

if [ ! -d "$SRC" ]; then
  echo "Error: source not found: $SRC"
  exit 1
fi

SRC="$(cd "$SRC" && pwd)"                 # Convert to absolute path
PARENT="$(dirname "$SRC")"
NAME="$(basename "$SRC")"
MODERNIZED="${PARENT}/${NAME}-modernized"
BRANCH="modernize/${TARGET}"

if [ -e "$MODERNIZED" ]; then
  echo "Error: target already exists: $MODERNIZED"
  exit 1
fi

# Ignore build artifacts
#   Priority 1: modernized-gitignore.template in the same directory as this script (provided by the Playbook, placed by install.sh)
#   Priority 2: file specified by the MODERNIZED_IGNORE_FILE environment variable
#   Fallback: minimal generic patterns (*adjust to match the build system in Step 1)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
write_artifact_gitignore() {
  local dst="$1"
  local src="${MODERNIZED_IGNORE_FILE:-$SCRIPT_DIR/modernized-gitignore.template}"
  if [ -f "$src" ]; then
    { echo ""; cat "$src"; } >> "$dst"
    echo "  (gitignore: applied $src)"
  else
    cat >> "$dst" <<'EOF'

# --- [port] build artifacts (generic fallback / adjust to match the build system) ---
# Only minimal patterns applied because the Playbook's modernized-gitignore.template was not found.
*~
*.log
*.tmp
EOF
    echo "  (gitignore: applied generic fallback — adjustment needed)"
  fi
}

echo "=== Setting up modernized tree ==="
echo "  source : $SRC"
echo "  modernized : $MODERNIZED"
echo "  branch : $BRANCH"

if git -C "$SRC" rev-parse --git-dir >/dev/null 2>&1; then
  # ---- git-managed source: clone + branch + modernize-base ----
  MODE="git-clone"
  git clone "$SRC" "$MODERNIZED"
  cd "$MODERNIZED"
  git fetch --all --tags >/dev/null 2>&1 || true
  if [ -n "$BASE_REF" ]; then
    git switch -c "$BRANCH" "$BASE_REF"
  else
    git switch -c "$BRANCH"
  fi
  BASE_SHA="$(git rev-parse HEAD)"
  git tag modernize-base
  # Respect upstream .gitignore, only appending artifacts generated by the migration
  touch .gitignore
  write_artifact_gitignore .gitignore
  git add .gitignore
  git commit -q -m "[port] add build-artifact ignores for ${TARGET}"
else
  # ---- non-git source: copy + init + modernize-base ----
  MODE="copy-init"
  cp -a "$SRC" "$MODERNIZED"
  cd "$MODERNIZED"
  rm -rf .git 2>/dev/null || true
  : > .gitignore
  write_artifact_gitignore .gitignore
  git init -q
  git add -A
  git commit -q -m "Initial commit: ${NAME} modernized source tree (${TARGET})"
  git branch -m "$BRANCH"
  BASE_SHA="$(git rev-parse HEAD)"
  git tag modernize-base
fi

echo ""
echo "=== Done ($MODE) ==="
echo "  modernized   : $MODERNIZED"
echo "  branch    : $BRANCH"
echo "  modernize-base : $BASE_SHA"
echo ""
echo "Next, record the following in the \"starting-point information\" of the migration project's session-context.md / work-plan.md:"
echo "  - Source tree     : $SRC  (mode=$MODE)"
echo "  - Starting base-ref  : ${BASE_REF:-HEAD}"
echo "  - Starting SHA(modernize-base): $BASE_SHA"
echo "  - modernize branch        : $BRANCH"
echo ""
echo "You can view the change diff at any time with: (cd $MODERNIZED && git diff modernize-base..HEAD)"
